### PR TITLE
disable gh-page jekyll build

### PR DESCRIPTION
**Pull request by X7md**
Disable `gh-page jekyll` build, should make deploy a little bit faster...    
https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

### CODE REVIEW

**Comment by X7md** [comment]
Preview:  https://git.x7md.net/tsoding-jaibreak/

**Comment by puttehi** [comment]
Should the aspect ratio be kept in all conditions? Currently it stretches according to window size, so doesn't look so great (except when at full size):

**Comment by X7md** [comment]
> Should the aspect ratio be kept in all conditions? Currently it stretches according to window size, so doesn't look so great (except when at full size): 

oh yeah, but looks #4 have nice response solution

**Review by mhzryyy8 — COMMENTED** [review]
Jailbeark

**Pull request closed without merging**
