### PR TITLE
add Persian (Farsi) language

### PR DESCRIPTION
**Pull request by HKhademian**
Hi,
This is Farsi/Persian translation from EN language file.
Persian is my native language.

### CODE REVIEW

**Comment by HKhademian** [comment]
I think to prevent spam and misuses please use google translate to check my/any translations: 

https://translate.google.com/?sl=fa&tl=en&op=translate

whole translation check :

https://translate.google.com/?sl=fa&tl=en&text=%D9%81%D8%A7%D8%B1%D8%B3%DB%8C%0A(%D8%A8%D8%B1%D8%A7%DB%8C%20%D8%B4%D8%B1%D9%88%D8%B9%20%D8%AF%D9%88%D8%A8%D8%A7%D8%B1%D9%87%20%27%D8%A7%D8%B3%D9%BE%DB%8C%D8%B3%27%20%D8%A8%D8%B2%D9%86%DB%8C%D8%AF)%0A%D8%AA%D9%88%D9%82%D9%81%0A%D8%A8%D8%B1%D8%A7%DB%8C%20%D8%AD%D8%B1%DA%A9%D8%AA%20%D8%A7%D8%B2%20%DA%A9%D9%84%DB%8C%D8%AF%20%27%DA%86%D9%BE%27%20%D9%88%20%27%D8%B1%D8%A7%D8%B3%D8%AA%27%20%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87%20%DA%A9%D9%86%DB%8C%D8%AF%0A%D8%A8%D8%B1%D8%A7%DB%8C%20%D8%B4%D8%B1%D9%88%D8%B9%20%27%D8%A7%D8%B3%D9%BE%DB%8C%D8%B3%27%20%D8%A8%D8%B2%D9%86%DB%8C%D8%AF%0A%D8%A7%D8%AA%D9%85%D8%A7%D9%85%20%D8%A8%D8%A7%D8%B2%DB%8C%0A%D8%A7%D9%85%D8%AA%DB%8C%D8%A7%D8%B2%3A%20%0A&op=translate

**Comment by rexim** [comment]
Nice! First right-to-left language! Thank you so much!

Just a quick question. Would it make sense to move the "Score: " label to the right side for Persian? I'm planning to implement some mechanism that changes the UI depending on the direction of the script.

So it would look something like this:
persian-rtl

**Comment by rexim** [comment]
I've been playing with this idea and realized that moving lifebar and score to the right might be someone's preference regardless of their language. So I'm gonna simply make it a separate option in the future.

Thanks for the translation once again! :+1:

**Comment by HKhademian** [comment]
Thanks , in fact it's common for RTL languages to use it like you implemented. 

<score> : RTL_SCORE_MSG

**Comment by rexim** [comment]
@HKhademian got it! Thanks!

**Pull request merged**
